
CREATE TABLE IF NOT EXISTS conversations (
    id INT PRIMARY KEY AUTOINCREMENT,
    title TEXT, 
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
)